# Generated by Django 4.0.6 on 2022-08-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('EDV', models.CharField(max_length=15)),
                ('idAreaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='api.areas')),
            ],
        ),
    ]
